def print_tell(num):
    print(num, end ='')
print_tell("8")
print_tell("8")
print_tell("0")
print_tell("0")
print_tell("5")
print_tell("5")
print_tell("5")
print_tell("5")
print_tell("3")
print_tell("5")
print_tell("3")
print_tell("5")